### ISSUE TITLE
Update 'watch' option in mkdocs.yml

### ISSUE THREAD

**Issue by pheus** [netbox-community/cookiecutter-netbox-plugin#21]
### cookiecutter-netbox-plugin version

main (d9200390ce1582f4e3eba757c1dabe6f6e27b2d3)

### Python version

3.12

### Steps to Reproduce

The generated mkdocs.yml file contains the `watch` configuration for `mkdocstrings`, which is no longer supported.

1. Run `cookiecutter https://github.com/netbox-community/cookiecutter-netbox-plugin.git`
2. Fill out the default values
3. Check generated mkdocs.yml

### Expected Behavior

The `watch` configuration is supported by mkdocs.

```yaml
plugins:
  - include-markdown
  - search:
      lang: en
watch:
  - netbox_acl_plugin
```

### Observed Behavior

The generated mkdocs.yml file contains the following configuration:

```yaml
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - netbox-acl-plugin
```

Running mkdocs v1.6.0 with mkdocsstrings v0.25.2 does throw a warning:
```shell
WARNING -  Config value 'plugins': Plugin 'mkdocstrings' option 'watch': Unrecognised configuration
           name: watch
```
