### ISSUE TITLE
Update to `slugify` function of markdown_extensions (DeprecationWarning)

### ISSUE THREAD

**Issue by pheus** [netbox-community/cookiecutter-netbox-plugin#22]
### cookiecutter-netbox-plugin version

main (d9200390ce1582f4e3eba757c1dabe6f6e27b2d3)

### Python version

3.12

### Steps to Reproduce

1. Run `cookiecutter https://github.com/netbox-community/cookiecutter-netbox-plugin.git`
2. Fill out the default values
3. Run `mkdocs serve -a localhost:8080`

### Expected Behavior

```yaml
markdown_extensions:
[...]
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
```

### Observed Behavior

(Snippet from the generated mkdocs.yml with default values)

```yaml
markdown_extensions:
[...]
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
```

```shell
INFO    -  DeprecationWarning: 'uslugify' is deprecated. 'uslugify' is deprecated in favor of the
           configurable 'slugify' function. See documentation for more info.
```
